#!/usr/bin/env bash
# Enable a continuous development environment. Will watch files for changes
#   and rebuild.

if [ "$1" == "--single-run" ] || [ "$1" == '-s' ]; then
  ./node_modules/.bin/grunt build_bulbs_cms_for_django
else
  ./node_modules/.bin/grunt watch
fi
